name = "Network_JSON_Reader"
uuid = "8713a39e-884f-488f-ad7e-bbee08dcc36b"
authors = ["HaSaeed <>\u001b[Dhshasan.saeed@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
